import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "liquidcn/styles.css";
import Provider from "@/provider";
import { Navbar } from "@/components/navbar";
import { AppFooter } from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        <Provider>
          <div className="mx-auto w-full max-w-5xl relative z-10 min-h-screen flex flex-col">
            <Navbar />
            <main className="flex-1 px-2 pb-16 pt-8 sm:px-4 sm:pt-12">
              {children}
            </main>
            <AppFooter />
          </div>
        </Provider>
      </body>
    </html>
  );
}
